# Netlify Configuration for Washington WizKids
# Optimized for Next.js 14 deployment

[build]
  # Build command
  command = "npm run build"
  
  # Output directory
  publish = ".next"

[build.environment]
  # Node version
  NODE_VERSION = "18.0.0"
  
  # Next.js specific settings
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

